import type { Metadata } from "next";
import Header from "./components/shared/Header";
import "./globals.css";



export const metadata: Metadata = {
  title: "E-commerce Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=""
      suppressHydrationWarning
      >
        <main className="p-2">
          <Header/>
        {children}
        </main>
      </body>
    </html>
  );
}
